### ISSUE TITLE
Sequence doesn't seem to be respecting my options (next/prev button defaults unclear)

### ISSUE THREAD

**Issue by Kerrick** [IanLunn/Sequence#73]
Version: 0.5.2 Beta

I've set Sequence up like so:

``` javascript
$(document).ready(function () {
  var sequence = $('#sequence').sequence({
    preloader: false,
    animateStartingFrameIn: true,
    nextButton: true,
    prependNextButton: false,
    prevButton: true,
    prependPrevButton: false,
    pauseIcon: true,
    prependPauseIcon: false
  }).data('sequence');
});
```

``` html
<div id="sequence">
  <ul>
    <li class="sequence-item websites">
      <h2 class="animate-in">Web design and development</h2>
      <p class="animate-in">From a single-page small business website to a full-featured web application, we do it all. Using modern technologies and best practices, we can develop one website that works on computers, smartphones, and tablets! And it's all available at an affordable price.</p>
      <a class="animate-in call-to-action" href="/websites/">Learn More &raquo;</a>
      <img class="animate-in image-one" src="images/devices/phone-kerricklong.png" width="195" height="383" alt="Screenshot of kerricklong.ocm on a phone" />
      <img class="animate-in image-two" src="images/devices/laptop-kerricklong.png" width="440" height="248" alt="Screenshot of kerricklong.com on a laptop" />
    </li>
    <li class="sequence-item photo-video">
      <h2>Photography and Video Services</h2>
      <p>Websites and marketing materials are great, but to really attract customers you need powerful imagery. Our photographers and videographers ready to shoot and film your business so you can bootstrap your marketing with professional, personalized media.</p>
      <a class="call-to-action" href="/photovideo/">Learn More &raquo;</a>
    </li>
    <li class="sequence-item something">
      <h2>Some other service offering</h2>
      <p>Write some copy here!</p>
      <a class="call-to-action" href="/something/">Learn More &raquo;</a>
    </li>
    <li class="sequence-item social-media">
      <h2>Social media strategies</h2>
      <p>Write some copy here!</p>
      <a class="call-to-action" href="/social-media/">Learn More &raquo;</a>
    </li>
  </ul>
  <b class="next"><i class="icon-r" data-icon="&#xf04e;">Next</i></b>
  <b class="prev"><i class="icon-r" data-icon="&#xf04a;">Previous</i></b>
  <b class="pause-icon"><i class="icon-r" data-icon="&#xf04c;">Pause</i></b>
</div>
```

``` css
#sequence{-webkit-border-radius:6px;-moz-border-radius:6px;-ms-border-radius:6px;-o-border-radius:6px;border-radius:6px;background:#222222;padding:24px;color:#ffcc00;height:384px;position:relative;overflow:hidden;}
#sequence > b{position:absolute;bottom:24px;right:24px;}
#sequence > b.prev{right:72px;}
#sequence > b.pause-icon{right:48px;}
.sequence-item > *{-webkit-transition-duration:0.5s;-moz-transition-duration:0.5s;-ms-transition-duration:0.5s;-o-transition-duration:0.5s;transition-duration:0.5s;position:absolute;}
.sequence-item > *.animate-in{-webkit-transition-duration:1s;-moz-transition-duration:1s;-ms-transition-duration:1s;-o-transition-duration:1s;transition-duration:1s;}
.sequence-item > *.animate-out{-webkit-transition-duration:0.5s;-moz-transition-duration:0.5s;-ms-transition-duration:0.5s;-o-transition-duration:0.5s;transition-duration:0.5s;}
.sequence-item h2{text-transform:uppercase;font-family:"Oswald Bold", "Helvetica Neue", Helvetica, Arial, sans-serif;font-weight:700;font-size:48px;line-height:60px;left:480px;top:-216px;width:432px;height:144px;text-align:center;}
.sequence-item h2.animate-in{top:24px;}
.sequence-item h2.animate-out{top:456px;}
.sequence-item p{font-size:24px;line-height:36px;left:960px;top:156px;width:432px;height:192px;}
.sequence-item p.animate-in{left:480px;}
.sequence-item p.animate-out{left:-432px;}
.sequence-item .call-to-action{height:48px;width:192px;background:#ffcc00;color:#222222;left:504px;top:432px;}
.sequence-item .call-to-action.animate-in{top:360px;}
.sequence-item .call-to-action.animate-out{top:-48px;}
.sequence-item .image-one{left:24px;top:-408px;}
.sequence-item .image-one.animate-in{top:24px;}
.sequence-item .image-one.animate-out{top:432px;}
.sequence-item .image-two{left:-480px;top:168px;}
.sequence-item .image-two.animate-in{left:24px;}
.sequence-item .image-two.animate-out{left:960px;}
.sequence-item img{border:0;}
```

You can view it in action here: http://zaltin.com/ (Note I've let the images 404 so you can see the next/prev buttons through them.)

Sequence doesn't seem to be respecting my options. It inserts a previous, next, and pause button even though I've told it not to. Plus, the pause button appears and disappears based on where your mouse cursor is. Further, it won't advance past slide one.

Am I doing something wrong, or is this a bug in sequence?
